org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=midnightthoughts
mod_name=Midnight Thoughts
mod_license=MIT
mod_version=1.5.1+forge.1.20.1
mod_group_id=midnightthoughts
mod_authors=iliiasik
mod_description=Diversify your gameplay and sleep mechanics with a comfort system, bedtime facts, nightmares, and general statistics since your last sleep. With full server support and convenient tools for building your world's lore through sleep facts and achievements

# KubeJS integration (optional / compile-only)
kubejs_version=2001.6.5-build.26
rhino_version=2001.2.2-build.17