org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.219
neoforge_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=midnightthoughts
mod_name=mthoughts
mod_license=MIT
mod_version=1.4.2+neoforge.1.21.1
mod_group_id=midnightthoughts
mod_authors=Iliiasik
mod_description=