modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mixins]]
config = "mthoughts.mixins.json"

[[mods]]
modId = "midnightthoughts"
version = "1.4.05"
displayName = "Midnight Thoughts"
logoFile = "assets/midnightthoughts/icon.png"
authors = "iliiasik"
description = '''A unique reworking of the sleep mechanics, with player stats since the last sleep, a comfort and rest system, the addition of sleep-related facts, achievements, or both, and customization. Full server support and server-side customization are also included'''

[[dependencies.midnightthoughts]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.midnightthoughts]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"